kind: pipeline
type: docker
name: default

steps:
- name: Push image
  image: hb.k8sbridge.com/library/docker:20.13.0
  settings:
    registry: hb.k8sbridge.com
    repo: hb.k8sbridge.com/library/example-drone-ci
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    debug: true
- name: deploy
  image: hb.k8sbridge.com/library/drone-kubernetes:latest
  settings:
    server: https://192.168.1.170:6443
    token: 
      from_secret: kubernetes_token
    template: ./manifests