kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: hb.k8sbridge.com/library/alpine:latest
  commands:
  - echo hello
  - echo world
- name: Push image
  image: hb.k8sbridge.com/library/docker:20.13.0
  settings:
    registry: hb.k8sbridge.com
    repo: hb.k8sbridge.com/library/example-drone-ci
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    insecure: true
    debug: true
