apiVersion : apps/v1
kind: Deployment
metadata:
  name: example-drone-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-drone-ci
  template:
    metadata:
      labels:
        app: example-drone-ci
    spec:
      containers:
        - name: hellovue 
          image: hb.k8sbridge.com/library/example-drone-ci
          ports:
          - containerPort: 8080
